// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuf/Message.proto

package Myfox.ProtoBuf;

public final class MessageProbuf {
  private MessageProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 senderid = 1;</code>
     */
    boolean hasSenderid();
    /**
     * <code>required int32 senderid = 1;</code>
     */
    int getSenderid();

    /**
     * <code>required string sendername = 2;</code>
     */
    boolean hasSendername();
    /**
     * <code>required string sendername = 2;</code>
     */
    java.lang.String getSendername();
    /**
     * <code>required string sendername = 2;</code>
     */
    com.google.protobuf.ByteString
        getSendernameBytes();

    /**
     * <code>required string senderip = 3;</code>
     */
    boolean hasSenderip();
    /**
     * <code>required string senderip = 3;</code>
     */
    java.lang.String getSenderip();
    /**
     * <code>required string senderip = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderipBytes();

    /**
     * <code>required string senderpwd = 4;</code>
     */
    boolean hasSenderpwd();
    /**
     * <code>required string senderpwd = 4;</code>
     */
    java.lang.String getSenderpwd();
    /**
     * <code>required string senderpwd = 4;</code>
     */
    com.google.protobuf.ByteString
        getSenderpwdBytes();

    /**
     * <code>required string sendtext = 5;</code>
     */
    boolean hasSendtext();
    /**
     * <code>required string sendtext = 5;</code>
     */
    java.lang.String getSendtext();
    /**
     * <code>required string sendtext = 5;</code>
     */
    com.google.protobuf.ByteString
        getSendtextBytes();

    /**
     * <code>required int32 receiverid = 6;</code>
     */
    boolean hasReceiverid();
    /**
     * <code>required int32 receiverid = 6;</code>
     */
    int getReceiverid();

    /**
     * <code>required string receivername = 7;</code>
     */
    boolean hasReceivername();
    /**
     * <code>required string receivername = 7;</code>
     */
    java.lang.String getReceivername();
    /**
     * <code>required string receivername = 7;</code>
     */
    com.google.protobuf.ByteString
        getReceivernameBytes();

    /**
     * <code>required string receiverip = 8;</code>
     */
    boolean hasReceiverip();
    /**
     * <code>required string receiverip = 8;</code>
     */
    java.lang.String getReceiverip();
    /**
     * <code>required string receiverip = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiveripBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              senderid_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sendername_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              senderip_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              senderpwd_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sendtext_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              receiverid_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              receivername_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              receiverip_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Myfox.ProtoBuf.MessageProbuf.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Myfox.ProtoBuf.MessageProbuf.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Myfox.ProtoBuf.MessageProbuf.Message.class, Myfox.ProtoBuf.MessageProbuf.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderid_;
    /**
     * <code>required int32 senderid = 1;</code>
     */
    public boolean hasSenderid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 senderid = 1;</code>
     */
    public int getSenderid() {
      return senderid_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 2;
    private java.lang.Object sendername_;
    /**
     * <code>required string sendername = 2;</code>
     */
    public boolean hasSendername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sendername = 2;</code>
     */
    public java.lang.String getSendername() {
      java.lang.Object ref = sendername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendername_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sendername = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSendernameBytes() {
      java.lang.Object ref = sendername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERIP_FIELD_NUMBER = 3;
    private java.lang.Object senderip_;
    /**
     * <code>required string senderip = 3;</code>
     */
    public boolean hasSenderip() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string senderip = 3;</code>
     */
    public java.lang.String getSenderip() {
      java.lang.Object ref = senderip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderipBytes() {
      java.lang.Object ref = senderip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERPWD_FIELD_NUMBER = 4;
    private java.lang.Object senderpwd_;
    /**
     * <code>required string senderpwd = 4;</code>
     */
    public boolean hasSenderpwd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string senderpwd = 4;</code>
     */
    public java.lang.String getSenderpwd() {
      java.lang.Object ref = senderpwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderpwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderpwd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSenderpwdBytes() {
      java.lang.Object ref = senderpwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderpwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTEXT_FIELD_NUMBER = 5;
    private java.lang.Object sendtext_;
    /**
     * <code>required string sendtext = 5;</code>
     */
    public boolean hasSendtext() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string sendtext = 5;</code>
     */
    public java.lang.String getSendtext() {
      java.lang.Object ref = sendtext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendtext_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sendtext = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSendtextBytes() {
      java.lang.Object ref = sendtext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendtext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERID_FIELD_NUMBER = 6;
    private int receiverid_;
    /**
     * <code>required int32 receiverid = 6;</code>
     */
    public boolean hasReceiverid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 receiverid = 6;</code>
     */
    public int getReceiverid() {
      return receiverid_;
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 7;
    private java.lang.Object receivername_;
    /**
     * <code>required string receivername = 7;</code>
     */
    public boolean hasReceivername() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string receivername = 7;</code>
     */
    public java.lang.String getReceivername() {
      java.lang.Object ref = receivername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receivername_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receivername = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReceivernameBytes() {
      java.lang.Object ref = receivername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receivername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERIP_FIELD_NUMBER = 8;
    private java.lang.Object receiverip_;
    /**
     * <code>required string receiverip = 8;</code>
     */
    public boolean hasReceiverip() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string receiverip = 8;</code>
     */
    public java.lang.String getReceiverip() {
      java.lang.Object ref = receiverip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiverip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiverip = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveripBytes() {
      java.lang.Object ref = receiverip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      senderid_ = 0;
      sendername_ = "";
      senderip_ = "";
      senderpwd_ = "";
      sendtext_ = "";
      receiverid_ = 0;
      receivername_ = "";
      receiverip_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSenderid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderpwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendtext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiverid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceivername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiverip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, senderid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSendernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSenderipBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSenderpwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSendtextBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, receiverid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getReceivernameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getReceiveripBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSendernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSenderipBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSenderpwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSendtextBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, receiverid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getReceivernameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getReceiveripBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Myfox.ProtoBuf.MessageProbuf.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Myfox.ProtoBuf.MessageProbuf.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        Myfox.ProtoBuf.MessageProbuf.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Myfox.ProtoBuf.MessageProbuf.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Myfox.ProtoBuf.MessageProbuf.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Myfox.ProtoBuf.MessageProbuf.Message.class, Myfox.ProtoBuf.MessageProbuf.Message.Builder.class);
      }

      // Construct using Myfox.ProtoBuf.MessageProbuf.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senderid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendername_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        senderip_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        senderpwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sendtext_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        receiverid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        receivername_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        receiverip_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Myfox.ProtoBuf.MessageProbuf.internal_static_Message_descriptor;
      }

      public Myfox.ProtoBuf.MessageProbuf.Message getDefaultInstanceForType() {
        return Myfox.ProtoBuf.MessageProbuf.Message.getDefaultInstance();
      }

      public Myfox.ProtoBuf.MessageProbuf.Message build() {
        Myfox.ProtoBuf.MessageProbuf.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Myfox.ProtoBuf.MessageProbuf.Message buildPartial() {
        Myfox.ProtoBuf.MessageProbuf.Message result = new Myfox.ProtoBuf.MessageProbuf.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderid_ = senderid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendername_ = sendername_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.senderip_ = senderip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.senderpwd_ = senderpwd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sendtext_ = sendtext_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.receiverid_ = receiverid_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.receivername_ = receivername_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.receiverip_ = receiverip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Myfox.ProtoBuf.MessageProbuf.Message) {
          return mergeFrom((Myfox.ProtoBuf.MessageProbuf.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Myfox.ProtoBuf.MessageProbuf.Message other) {
        if (other == Myfox.ProtoBuf.MessageProbuf.Message.getDefaultInstance()) return this;
        if (other.hasSenderid()) {
          setSenderid(other.getSenderid());
        }
        if (other.hasSendername()) {
          bitField0_ |= 0x00000002;
          sendername_ = other.sendername_;
          onChanged();
        }
        if (other.hasSenderip()) {
          bitField0_ |= 0x00000004;
          senderip_ = other.senderip_;
          onChanged();
        }
        if (other.hasSenderpwd()) {
          bitField0_ |= 0x00000008;
          senderpwd_ = other.senderpwd_;
          onChanged();
        }
        if (other.hasSendtext()) {
          bitField0_ |= 0x00000010;
          sendtext_ = other.sendtext_;
          onChanged();
        }
        if (other.hasReceiverid()) {
          setReceiverid(other.getReceiverid());
        }
        if (other.hasReceivername()) {
          bitField0_ |= 0x00000040;
          receivername_ = other.receivername_;
          onChanged();
        }
        if (other.hasReceiverip()) {
          bitField0_ |= 0x00000080;
          receiverip_ = other.receiverip_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderid()) {
          
          return false;
        }
        if (!hasSendername()) {
          
          return false;
        }
        if (!hasSenderip()) {
          
          return false;
        }
        if (!hasSenderpwd()) {
          
          return false;
        }
        if (!hasSendtext()) {
          
          return false;
        }
        if (!hasReceiverid()) {
          
          return false;
        }
        if (!hasReceivername()) {
          
          return false;
        }
        if (!hasReceiverip()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Myfox.ProtoBuf.MessageProbuf.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Myfox.ProtoBuf.MessageProbuf.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int senderid_ ;
      /**
       * <code>required int32 senderid = 1;</code>
       */
      public boolean hasSenderid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 senderid = 1;</code>
       */
      public int getSenderid() {
        return senderid_;
      }
      /**
       * <code>required int32 senderid = 1;</code>
       */
      public Builder setSenderid(int value) {
        bitField0_ |= 0x00000001;
        senderid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 senderid = 1;</code>
       */
      public Builder clearSenderid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sendername_ = "";
      /**
       * <code>required string sendername = 2;</code>
       */
      public boolean hasSendername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sendername = 2;</code>
       */
      public java.lang.String getSendername() {
        java.lang.Object ref = sendername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendername_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sendername = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSendernameBytes() {
        java.lang.Object ref = sendername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sendername = 2;</code>
       */
      public Builder setSendername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sendername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sendername = 2;</code>
       */
      public Builder clearSendername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendername_ = getDefaultInstance().getSendername();
        onChanged();
        return this;
      }
      /**
       * <code>required string sendername = 2;</code>
       */
      public Builder setSendernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sendername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderip_ = "";
      /**
       * <code>required string senderip = 3;</code>
       */
      public boolean hasSenderip() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string senderip = 3;</code>
       */
      public java.lang.String getSenderip() {
        java.lang.Object ref = senderip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderipBytes() {
        java.lang.Object ref = senderip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderip = 3;</code>
       */
      public Builder setSenderip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        senderip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderip = 3;</code>
       */
      public Builder clearSenderip() {
        bitField0_ = (bitField0_ & ~0x00000004);
        senderip_ = getDefaultInstance().getSenderip();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderip = 3;</code>
       */
      public Builder setSenderipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        senderip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderpwd_ = "";
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public boolean hasSenderpwd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public java.lang.String getSenderpwd() {
        java.lang.Object ref = senderpwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderpwd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSenderpwdBytes() {
        java.lang.Object ref = senderpwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderpwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public Builder setSenderpwd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        senderpwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public Builder clearSenderpwd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        senderpwd_ = getDefaultInstance().getSenderpwd();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderpwd = 4;</code>
       */
      public Builder setSenderpwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        senderpwd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sendtext_ = "";
      /**
       * <code>required string sendtext = 5;</code>
       */
      public boolean hasSendtext() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string sendtext = 5;</code>
       */
      public java.lang.String getSendtext() {
        java.lang.Object ref = sendtext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sendtext_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sendtext = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSendtextBytes() {
        java.lang.Object ref = sendtext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendtext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sendtext = 5;</code>
       */
      public Builder setSendtext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sendtext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sendtext = 5;</code>
       */
      public Builder clearSendtext() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sendtext_ = getDefaultInstance().getSendtext();
        onChanged();
        return this;
      }
      /**
       * <code>required string sendtext = 5;</code>
       */
      public Builder setSendtextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sendtext_ = value;
        onChanged();
        return this;
      }

      private int receiverid_ ;
      /**
       * <code>required int32 receiverid = 6;</code>
       */
      public boolean hasReceiverid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 receiverid = 6;</code>
       */
      public int getReceiverid() {
        return receiverid_;
      }
      /**
       * <code>required int32 receiverid = 6;</code>
       */
      public Builder setReceiverid(int value) {
        bitField0_ |= 0x00000020;
        receiverid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 receiverid = 6;</code>
       */
      public Builder clearReceiverid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        receiverid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object receivername_ = "";
      /**
       * <code>required string receivername = 7;</code>
       */
      public boolean hasReceivername() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string receivername = 7;</code>
       */
      public java.lang.String getReceivername() {
        java.lang.Object ref = receivername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receivername_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receivername = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReceivernameBytes() {
        java.lang.Object ref = receivername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receivername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receivername = 7;</code>
       */
      public Builder setReceivername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        receivername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receivername = 7;</code>
       */
      public Builder clearReceivername() {
        bitField0_ = (bitField0_ & ~0x00000040);
        receivername_ = getDefaultInstance().getReceivername();
        onChanged();
        return this;
      }
      /**
       * <code>required string receivername = 7;</code>
       */
      public Builder setReceivernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        receivername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverip_ = "";
      /**
       * <code>required string receiverip = 8;</code>
       */
      public boolean hasReceiverip() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string receiverip = 8;</code>
       */
      public java.lang.String getReceiverip() {
        java.lang.Object ref = receiverip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiverip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiverip = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveripBytes() {
        java.lang.Object ref = receiverip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiverip = 8;</code>
       */
      public Builder setReceiverip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        receiverip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverip = 8;</code>
       */
      public Builder clearReceiverip() {
        bitField0_ = (bitField0_ & ~0x00000080);
        receiverip_ = getDefaultInstance().getReceiverip();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiverip = 8;</code>
       */
      public Builder setReceiveripBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        receiverip_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ProtoBuf/Message.proto\"\244\001\n\007Message\022\020\n\010" +
      "senderid\030\001 \002(\005\022\022\n\nsendername\030\002 \002(\t\022\020\n\010se" +
      "nderip\030\003 \002(\t\022\021\n\tsenderpwd\030\004 \002(\t\022\020\n\010sendt" +
      "ext\030\005 \002(\t\022\022\n\nreceiverid\030\006 \002(\005\022\024\n\014receive" +
      "rname\030\007 \002(\t\022\022\n\nreceiverip\030\010 \002(\tB\037\n\016Myfox" +
      ".ProtoBufB\rMessageProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Senderid", "Sendername", "Senderip", "Senderpwd", "Sendtext", "Receiverid", "Receivername", "Receiverip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
