#!/bin/bash
#this script starts client
pwd
javac -d ./target -cp /home/kourui/netty4125/netty-4.1.25.Final/jar/all-in-one/netty-all-4.1.25.Final.jar:/home/kourui/protobuf-java-2.6.1.jar -sourcepath /home/kourui/servertestdemo/ -encoding UTF-8 ./Client/WelcomeUI.java