#!/bin/bash
#this script starts client
pwd
#javac -d ./target -cp /usr/share/java/mysql-connector-java-8.0.11.jar:/home/kourui/netty4125/netty-4.1.25.Final/jar/all-in-one/netty-all-4.1.25.Final.jar:/home/kourui/protobuf-java-2.6.1.jar -sourcepath /home/kourui/servertestdemo/ -encoding UTF-8 ./Server/ServerCtrl.java
javac -d ./target -cp /root/protobuf-java-2.6.1.jar:/root/connectorj/usr/share/java/mysql-connector-java-8.0.11.jar:/root/netty-4.1.25.Final/jar/all-in-one/netty-all-4.1.25.Final.jar -sourcepath /root/servertestdemo/ -encoding UTF-8 ./Server/ServerCtrl.java